#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and adds a custom response header

set -e

# Install Nginx
apt-get update -y
apt-get install -y nginx

# Insert custom header inside the server block of default site
sed -i "/^\s*server\s*{/a \    set_header X-Served-By %[srv_name];" /etc/nginx/sites-available/default

# Start Nginx using service
service nginx start
