#!/usr/bin/env bash
# Configures a new Ubuntu machine to serve a 301 redirect at /redirect_me

set -e

# Install nginx
apt-get update -y
apt-get install -y nginx

# Add redirect rule to default server config
# This inserts the redirect inside the server block
sed -i '/^\s*server\s*{/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Start nginx using service
service nginx start
